export const chisel_bzip2_argv = [
{ crash_loc: 9534, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 9783, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9791, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9876, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 7194, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10761, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9876, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10761, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 6848, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2475, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 445, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 6541, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 445, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2184, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9791, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3732, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 497, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 497, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2184, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 140710516648786, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2272, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10685, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 484, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 10685, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 902, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 685, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 685, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 9508, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 21, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "chisel" },
{ crash_loc: 4949, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10721, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10685, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10761, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10800, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10887, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10484, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 9876, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1481, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2176, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2184, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2186, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2187, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2188, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1805, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1817, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1830, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1837, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1837, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1829, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1843, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1969, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1995, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1997, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2006, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2006, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2328, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2350, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2350, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2434, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2435, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2436, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];