export const chisel_bzip2_input = [
{ crash_loc: 9781, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 9533, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: 9789, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 9555, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2474, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2106, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2226, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 7193, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2226, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2474, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2106, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10759, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3771, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3819, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3795, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3691, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 900, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3667, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3747, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3683, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3739, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3835, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3675, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3755, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3787, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3763, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3659, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3715, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3803, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3699, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3827, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3723, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3731, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3811, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3707, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3779, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3843, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 139859468810703, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2183, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2226, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2474, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2106, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2151, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94103937447705, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2519, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 6540, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 444, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3659, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3731, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3755, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 759, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 695, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2226, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2151, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2474, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2519, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2327, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 759, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 482, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 10683, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 1968, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 900, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 683, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2311, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 574, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2311, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 574, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 683, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 9507, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 20, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "chisel" },
{ crash_loc: 10759, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10798, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10885, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10482, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1480, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1804, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1829, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1836, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1836, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1828, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1842, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1968, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1994, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1996, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2004, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2004, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2327, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2349, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2349, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2433, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2434, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2435, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1816, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 643, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 642, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 655, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 655, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2065, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2066, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2067, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2175, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2185, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2186, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2187, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2445, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2446, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2197, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2198, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4948, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10719, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10683, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];