export const chisel_chown_argv = [
{ crash_loc: 4364, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 140538092869629, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94219090361582, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94460722322720, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94833809813421, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 47093592289700, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1585, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4364, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1604, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1634, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4318, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4364, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1604, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4364, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 4364, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 6853, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "chisel" },
{ crash_loc: 1521, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4364, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1604, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 1634, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4318, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];