export const chisel_rm_argv = [
{ crash_loc: 5612, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 4746, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: 5838, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 140013857581053, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1983, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1943, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1983, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4885, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1983, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1983, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1943, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1943, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1943, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 1983, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4891, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 5729, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 5775, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Chisel" },
{ crash_loc: 5775, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Chisel" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Chisel" },
{ crash_loc: 5838, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4885, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];