export const chisel_sort_input = [
{ crash_loc: 13881, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: 13881, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10020, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 140489070641130, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 13881, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94225655297178, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 13881, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 9724, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Chisel" },
{ crash_loc: 9724, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Chisel" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Chisel" },
{ crash_loc: 10054, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10055, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 11739, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 11740, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];