export const chisel_sort_argv = [
{ crash_loc: 13883, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 8992, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "chisel" },
{ crash_loc: "", vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "chisel" },
{ crash_loc: 13883, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 7783, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94463751333163, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10021, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 13883, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 11740, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 11774, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 13883, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 93859112695113, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 10055, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 9725, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Chisel" },
{ crash_loc: 9725, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Chisel" },
{ crash_loc: 10055, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 10056, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 11740, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 11741, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];