export const chisel_uniq_argv = [
{ crash_loc: 7208, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 6643, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 6625, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 6625, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 6178, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 94504516676784, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 7208, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 7208, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 94272500404669, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2308, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 2308, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 3, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 3, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 7208, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5870, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 6665, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 6625, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 6625, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
];