export const chisel_grep_input = [
{ crash_loc: 12504, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 12504, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10992, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 10992, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 16003, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 16062, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 21150, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 13529, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 13259, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 13259, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 26, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Chisel" },
{ crash_loc: 97, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 12581, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 996, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 773, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 1891, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 9, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 9, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 97, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 1891, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 97, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 12581, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 11043, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
];