export const chisel_gzip_input = [
{ crash_loc: 5031, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 4183, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 4741, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 5035, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 5029, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3630, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
{ crash_loc: 3230, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 3190, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 2356, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 2585, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 3182, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 4183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4183, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2669, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2604, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2356, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3230, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3190, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2675, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2676, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2585, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2586, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2243, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2243, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2139, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2139, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2243, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 3182, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3185, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3185, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3182, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2651, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2662, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2597, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3076, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3404, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3052, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4142, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 3186, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 2675, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 2243, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2243, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 2710, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 5023, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 94634461425050, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 1605, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 5407, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2610, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 2662, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 5138, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 4741, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 5407, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 5407, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 4558, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 3955, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5031, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5035, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5035, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5138, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5143, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5147, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3861, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3887, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5029, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5028, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 3892, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5407, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 5045, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5023, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5023, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 3893, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 5716, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4451, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4451, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4563, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4564, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 4564, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Chisel" },
{ crash_loc: 2548, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 5023, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 2139, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 3630, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Chisel" },
];