export const chisel_tar_input = [
{ crash_loc: 16025, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 29792, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 94148345947988, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 16025, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 17163, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 12046, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 2, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 17162, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 16549, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 16758, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 24195, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Chisel" },
{ crash_loc: 24027, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 24221, vul_type: "IssueCat-6 Write memory access", deb_tool: "Chisel" },
{ crash_loc: 24022, vul_type: "IssueCat-5 Read memory access", deb_tool: "Chisel" },
{ crash_loc: 12377, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
{ crash_loc: 12910, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Chisel" },
];