export const cova_bzip2_input = [
{ crash_loc: "", vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "cova" },
{ crash_loc: 7287, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 7287, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-6 Write memory access", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "cova" },
{ crash_loc: 10759, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 10774, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 10798, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 10772, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
];