export const cova_chown_argv = [
{ crash_loc: 1590, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 1547, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5839, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5158, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 1547, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6895, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 6901, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 5211, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 6561, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: "", vul_type: "IssueCat-6 Write memory access", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "cova" },
{ crash_loc: "", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "cova" },
{ crash_loc: 4065, vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "CovA" },
{ crash_loc: 6850, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
];