export const cova_gzip_argv = [
{ crash_loc: 6989, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6916, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6916, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 7439, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 8796, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 8802, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 8142, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 94189770428641, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 5944, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 8802, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 8142, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2663, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 7094, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 6388, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 7514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: "", vul_type: "IssueCat-13 Strcpy param overlap", deb_tool: "cova" },
{ crash_loc: 2493, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2663, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2598, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2526, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2573, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2631, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
];