export const cova_tar_argv = [
{ crash_loc: 21868, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5868, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 3422, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12385, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 8155, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12385, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12385, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 17429, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 21985, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2066, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 20493, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 20493, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 20581, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 20579, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12891, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 1494, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 1494, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 1494, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 16249, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 15066, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 1494, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20493, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20229, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20318, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20493, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20581, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 140721173769200, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20493, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20493, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 20581, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "cova" },
{ crash_loc: 30173, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15066, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15073, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 22984, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 22984, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 12098, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 22984, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 22800, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "cova" },
];