export const covf_date_argv = [
{ crash_loc: 2545, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "covf" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "covf" },
{ crash_loc: "", vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "covf" },
{ crash_loc: 9497, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 9497, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4669, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4669, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5122, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5397, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 9394, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 5128, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 5128, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "covf" },
{ crash_loc: 5111, vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "CovF" },
{ crash_loc: 3848, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5364, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2283, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5367, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4669, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4669, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5362, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4403, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5126, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5128, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
];