export const covf_grep_input = [
{ crash_loc: 21143, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 1143, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 439, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2654, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2654, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 23254, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 21149, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2654, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 21149, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-6 Write memory access", deb_tool: "covf" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "covf" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "covf" },
{ crash_loc: 21773, vul_type: "IssueCat-12 Negative size param", deb_tool: "CovF" },
{ crash_loc: 20113, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
];