export const covf_rm_argv = [
{ crash_loc: 2941, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "covf" },
{ crash_loc: 4455, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 94366596235388, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 6367, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 1944, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 1944, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 6969, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 1944, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 1944, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 4455, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 1944, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 1944, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "covf" },
{ crash_loc: 5776, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "CovF" },
{ crash_loc: 5776, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "CovF" },
{ crash_loc: 2713, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
];