export const covf_bzip2_input = [
{ crash_loc: 64, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 1829, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 61, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 1816, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 4729, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "CovF" },
{ crash_loc: 4729, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "CovF" },
{ crash_loc: 62, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 4, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 1829, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 61, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 1816, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 4729, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "CovF" },
{ crash_loc: 4729, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "CovF" },
{ crash_loc: 37, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 11650, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11653, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11656, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11659, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11672, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11687, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11979, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11081, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11082, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11093, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11094, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11105, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11106, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11117, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11118, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11129, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11130, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11141, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11142, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11153, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11154, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11165, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11166, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11981, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1829, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1836, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1836, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 643, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 642, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 655, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 655, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2172, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2175, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2258, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1804, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1828, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1842, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2184, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2185, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2186, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2187, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1816, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1968, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1993, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1996, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1997, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1994, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2004, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2004, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2007, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2506, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2169, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2519, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2197, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2198, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 655, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2358, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2359, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2064, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2065, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2066, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2067, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2078, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2078, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2432, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2184, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2741, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2226, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 1793, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "CovF" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "CovF" },
{ crash_loc: 2474, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2064, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 984, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 1631, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 984, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2432, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2184, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2741, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2226, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 1793, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2474, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2064, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 1631, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 7287, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 7287, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2138, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2432, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2433, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2434, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2435, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2421, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2421, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2446, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2311, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2311, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2198, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2431, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
];