export const covf_gzip_argv = [
{ crash_loc: 1606, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 1606, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5944, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 7439, vul_type: "IssueCat-13 Strcpy param overlap", deb_tool: "CovF" },
{ crash_loc: 5046, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 1731, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 1606, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 0, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 8142, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5046, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5024, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4942, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3881, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3873, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5111, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5115, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3862, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3888, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1731, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 1731, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 1731, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 7743, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 7743, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 5752, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 1606, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 6388, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
];