export const covf_gzip_input = [
{ crash_loc: 5029, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 5392, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5398, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5395, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5401, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2337, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2161, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2538, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2538, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2161, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 4631, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 4631, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2696, vul_type: "IssueCat-14 Memcpy param overlap", deb_tool: "CovF" },
{ crash_loc: 2161, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2538, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5029, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5028, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5716, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3861, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3887, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5045, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 5023, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4941, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4451, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4451, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4563, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4564, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4564, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4565, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5110, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2203, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2356, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2161, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2227, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 2356, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4631, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 3190, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 3230, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2642, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2313, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2643, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2643, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2139, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2139, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2618, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2642, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2532, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 2537, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 4563, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5045, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 5751, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2346, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2644, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2346, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2227, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 4631, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 3095, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2505, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 7741, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 8135, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 94692988303226, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 94383891105602, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 94514545227665, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5045, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 4565, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4563, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 5404, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5386, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5389, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovF" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 2346, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 4632, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
];