export const covf_sort_argv = [
{ crash_loc: 9725, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "CovF" },
{ crash_loc: 9725, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "CovF" },
{ crash_loc: 2, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 13883, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 8996, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4996, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 8300, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 8121, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 11774, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 140439810351676, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 94134446154471, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 139849556469162, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovF" },
{ crash_loc: 11774, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 13883, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 13689, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
];