export const covf_tar_input = [
{ crash_loc: 15072, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 15072, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "CovF" },
{ crash_loc: 24266, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 30086, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 94432701409449, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 17428, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 8154, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 12117, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 12384, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 12416, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 12890, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 29792, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 24251, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 24263, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 24221, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 24088, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 24104, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 24095, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 4142, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 140734203558224, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 140726214640240, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 140733080633136, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovF" },
{ crash_loc: 30086, vul_type: "IssueCat-9 Heap use after free", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "CovF" },
{ crash_loc: 28459, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 13142, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 28459, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 12384, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 12415, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovF" },
{ crash_loc: 28464, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 13046, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
{ crash_loc: 13142, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovF" },
{ crash_loc: 29587, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovF" },
];