export const cov_chown_argv = [
{ crash_loc: 4897, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 1580, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 5550, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 4897, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 1634, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 1582, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 4897, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 4912, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 4897, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 1582, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 5211, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 4400, vul_type: "IssueCat-6 Write memory access", deb_tool: "Cov" },
{ crash_loc: 4836, vul_type: "IssueCat-6 Write memory access", deb_tool: "Cov" },
{ crash_loc: 4836, vul_type: "IssueCat-6 Write memory access", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "cov" },
{ crash_loc: 5713, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "cov" },
{ crash_loc: 5713, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "cov" },
{ crash_loc: 4897, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
{ crash_loc: 1634, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
{ crash_loc: 4400, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
{ crash_loc: 5211, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
];