export const cov_tar_input = [
{ crash_loc: 17428, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 8154, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 12384, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 12416, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 12890, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 29792, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 24251, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 24263, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 24088, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 24104, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 12416, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: 15072, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Cov" },
{ crash_loc: 24266, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Cov" },
{ crash_loc: 30086, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Cov" },
{ crash_loc: 15072, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 12117, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 24095, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 29587, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 24221, vul_type: "IssueCat-6 Write memory access", deb_tool: "Cov" },
{ crash_loc: 4142, vul_type: "IssueCat-6 Write memory access", deb_tool: "Cov" },
{ crash_loc: 28464, vul_type: "IssueCat-6 Write memory access", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Cov" },
{ crash_loc: 30086, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Cov" },
];