export const cov_uniq_argv = [
{ crash_loc: 6612, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "cov" },
{ crash_loc: 7175, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 7175, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 7175, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 94371499613067, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 6625, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: 6625, vul_type: "IssueCat-5 Read memory access", deb_tool: "Cov" },
{ crash_loc: "", vul_type: "IssueCat-6 Write memory access", deb_tool: "cov" },
{ crash_loc: "", vul_type: "IssueCat-7 Direct Leak", deb_tool: "cov" },
{ crash_loc: 5870, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
{ crash_loc: 7175, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
{ crash_loc: 7175, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
{ crash_loc: 6665, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Cov" },
];