export const cova_date_argv = [
{ crash_loc: 9583, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 94003287832450, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 140046822457416, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 9321, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 139926619032605, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 5111, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 5111, vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "CovA" },
{ crash_loc: 5136, vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "CovA" },
{ crash_loc: 9497, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 9497, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6151, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 9449, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 9444, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 139842648972757, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 139919338458608, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 139709366112477, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 9285, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 9497, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 6151, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 6151, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 9394, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 4903, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 4914, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5242, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 9657, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 1514, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 4733, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5354, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5086, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 4762, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 9505, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 9505, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 9505, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 9505, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 5351, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 9664, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5128, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
];