export const cova_gzip_input = [
{ crash_loc: 5029, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5407, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5389, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5392, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 2643, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2643, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 2161, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 2337, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 2161, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 2538, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2696, vul_type: "IssueCat-14 Memcpy param overlap", deb_tool: "CovA" },
{ crash_loc: 5029, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 5028, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 5716, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 3861, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 3887, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2203, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2356, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2161, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2642, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2643, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2651, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2652, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2674, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2674, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 3190, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 3183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 3230, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2618, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 2643, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2346, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2346, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2644, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6914, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2139, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 3095, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2505, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2682, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2538, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2610, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2346, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2643, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 5404, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5401, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5398, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5386, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 5395, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
];