export const cova_rm_argv = [
{ crash_loc: 139964263480816, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 6952, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 4895, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6993, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 140558116636543, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 6401, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6278, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6370, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 6323, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 139860723052616, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 140633505459669, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 7074, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 7074, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 7074, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 7074, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
];