export const cova_sort_argv = [
{ crash_loc: 9019, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 9019, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 9688, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 9019, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 9019, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 4070, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 14277, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 10029, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 8518, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 8656, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 0, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 13475, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 13587, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 9019, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 14256, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "CovA" },
{ crash_loc: 14256, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 14256, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 13890, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 13890, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 13901, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 13901, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 13890, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 14256, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 14256, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 14256, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 13261, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 13273, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 13890, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 13890, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 13901, vul_type: "IssueCat-15 Runtime Error", deb_tool: "CovA" },
{ crash_loc: 13901, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 14262, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 14241, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 13890, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 14190, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 13936, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 13901, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
];