export const cova_tar_input = [
{ crash_loc: 15072, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 15072, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "CovA" },
{ crash_loc: 17428, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 8154, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12117, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
{ crash_loc: 12384, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12416, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 12890, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 29792, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 4142, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 12384, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 28459, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "CovA" },
{ crash_loc: 28464, vul_type: "IssueCat-6 Write memory access", deb_tool: "CovA" },
{ crash_loc: 28464, vul_type: "IssueCat-5 Read memory access", deb_tool: "CovA" },
];