export const blade_bzip2_input = [
{ crash_loc: 9789, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9555, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4995, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1480, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2175, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2183, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2184, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2185, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2186, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2187, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2327, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2327, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1829, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1836, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1836, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1804, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1828, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1842, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2172, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1816, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1994, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1996, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1997, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2004, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2004, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2005, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2007, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2506, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9781, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 9533, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 9507, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 9507, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 5003, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 4936, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 4934, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 11852, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4729, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 4729, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 7193, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: 11898, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11852, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11920, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11745, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11852, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 6540, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 29, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 520, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2226, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2711, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2208, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2519, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2151, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2106, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2474, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9507, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 9507, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 6847, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11879, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11837, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2226, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11920, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1828, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2183, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2327, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2078, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 4729, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 4729, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 3877, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3972, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11852, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 7248, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 2311, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 45, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 4729, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 4729, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 94202576651297, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3301, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3877, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11852, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11898, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2271, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
];