export const blade_chown_argv = [
{ crash_loc: 1619, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1619, vul_type: "IssueCat-11 Attempting free on address not malloced", deb_tool: "Blade" },
{ crash_loc: 4836, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1634, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4836, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4768, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4898, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 6901, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 47527349600593, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 94364976376546, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4829, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 4829, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4912, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1524, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 4327, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 1590, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 1580, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: 1525, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 7077, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: 7077, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: 1525, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4004, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 4837, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 4833, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
];