export const blade_grep_argv = [
{ crash_loc: 23172, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 10947, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 21151, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 7001, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 7001, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 23172, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3632, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 20032, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 21143, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 20365, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 15232, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 15280, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 15281, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5440, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 15281, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5440, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 7748, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 15333, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 20365, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11007, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11039, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11531, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 10876, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11013, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11013, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 13260, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 13260, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 10877, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 7001, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 20365, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 20365, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 20365, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11013, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 22428, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 7, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 11591, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 11230, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11600, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1045, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 1045, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 19213, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1045, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 1045, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 11399, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 569, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 19213, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
];