export const blade_mkdir_argv = [
{ crash_loc: 3550, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 3552, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 3552, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3552, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 3413, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3612, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 140137585138729, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 139748847476994, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 140330354908181, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 140662245313544, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 140673613364279, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 3550, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 5042, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 3413, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3413, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3550, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 4968, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 3552, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
];