export const blade_sort_argv = [
{ crash_loc: 13883, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 13883, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 7783, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 10055, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 10056, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11740, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11741, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11742, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11773, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11773, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 13689, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11774, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 8992, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 13883, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9725, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 9725, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
];