export const blade_bzip2_argv = [
{ crash_loc: 9534, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 9783, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9791, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9869, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 7194, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9869, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 6541, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 6848, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2227, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2272, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11854, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 93928313546592, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9791, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 139927192885711, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2184, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11854, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11922, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11854, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 5, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 140481487981394, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 94537807903746, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 94435997162502, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 11922, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 93958783817628, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 94039422642930, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 9540, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 11380, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 11380, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 5004, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 11736, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 94092399879152, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 94403768564921, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 9540, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 9536, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 9556, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 9521, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 9536, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 4730, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 4730, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 5, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: 140481487981394, vul_type: "IssueCat-9 Heap use after free", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 4730, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 9508, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 4730, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 11763, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11380, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 9869, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3509, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3517, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3878, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3973, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 1481, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2176, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2184, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2185, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2186, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2187, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2188, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
];