export const blade_gzip_input = [
{ crash_loc: 4155, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 2187, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 2139, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 3095, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 2330, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 3190, vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "blade" },
{ crash_loc: 4558, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 2525, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 2585, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 5029, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 5138, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 5035, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 5031, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 5386, vul_type: "IssueCat-4 Global buffer overflow", deb_tool: "Blade" },
{ crash_loc: 2538, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3182, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2525, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4741, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 3182, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2356, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4741, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4741, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1605, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 5386, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2139, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 2525, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4741, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 5386, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4155, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 2337, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 5, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-14 Memcpy param overlap", deb_tool: "blade" },
{ crash_loc: 4155, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2330, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2332, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2337, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2525, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 4741, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3182, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3230, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2336, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5029, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5028, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5031, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5035, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5035, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5138, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5143, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5147, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3861, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3887, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 5716, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 3892, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 2391, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
];