export const blade_rm_argv = [
{ crash_loc: 5613, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 4747, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "blade" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "blade" },
{ crash_loc: 4452, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4373, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1984, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 7001, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1944, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 6506, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1984, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 4455, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 5730, vul_type: "IssueCat-7 Direct Leak", deb_tool: "Blade" },
{ crash_loc: 5776, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 5776, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 4452, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 6579, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
];