export const blade_sort_input = [
{ crash_loc: 13881, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 13881, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "blade" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "blade" },
{ crash_loc: 13881, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 13881, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 93984860357031, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 13881, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 94011774236566, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 11772, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 9724, vul_type: "IssueCat-8 Allocation size too big", deb_tool: "Blade" },
{ crash_loc: 9724, vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: "UNRECOGNIZED_ERROR", vul_type: "IssueCat-10 Requested allocation size exceeds maximum supported size", deb_tool: "Blade" },
{ crash_loc: 10054, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 10055, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11739, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11740, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11741, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
{ crash_loc: 11772, vul_type: "IssueCat-15 Runtime Error", deb_tool: "Blade" },
];