export const blade_tar_argv = [
{ crash_loc: 21937, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: 22565, vul_type: "IssueCat-1 Use of uninitialized variable", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-2 Stack-based buffer overflow", deb_tool: "blade" },
{ crash_loc: 16026, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 16026, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 93995319577491, vul_type: "IssueCat-3 Heap-based buffer overflow", deb_tool: "Blade" },
{ crash_loc: 21552, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 21468, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1196, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 1196, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 24211, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 21468, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 16194, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 16194, vul_type: "IssueCat-5 Read memory access", deb_tool: "Blade" },
{ crash_loc: 21937, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 22565, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 93999698557727, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: 22800, vul_type: "IssueCat-6 Write memory access", deb_tool: "Blade" },
{ crash_loc: "", vul_type: "IssueCat-9 Heap use after free", deb_tool: "blade" },
];